cp /global/home/users/hannsode/genomes/Neurospora-tetrasperma_FGSC2508_FungiDB-3.1.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-sublineolata_FGSC5508.fasta .
cp /global/home/users/hannsode/genomes/P3-C1-8_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/neo-LNF9-4_06032016.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/Sordaria-macrospora_k-hell_FungiDB-3.1.fasta .
cp /global/home/users/hannsode/genomes/MI3-15_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/FGSC6877_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-discreta_FGSC8579_FungiDB-3.1.fasta .
cp /global/home/users/hannsode/genomes/W1111_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/MM23_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-terricola_FGSC1889.fasta .
cp /global/home/users/hannsode/genomes/neo-LNF9-14_06032016.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/neo-LNF8-2_06032016.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/neo-MI3-2_06032016.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/neo-LNF6-4_06032016.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-africana_FGSC1740.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-pannonica_FGSC7221.fasta .
cp /global/home/users/hannsode/genomes/P4-W1_10132017.final.scaffolds.fasta .
cp /global/home/users/hannsode/genomes/Neurospora-crassa_OR74A_v12_fixed.fasta .
